server:
  port: "8080"
  mode: "debug"

mysql_main:
  host: "103.145.190.207"
  port: 33806
  database: "wht_pay"
  username: "wht_pay"
  password: "7npGfyWibhrX8BYx"
  charset: "utf8mb4"
  maxIdleConns: 5
  maxOpenConns: 20

mysql_order:
  host: "103.145.190.207"
  port: 33806
  database: "wht_order"
  username: "wht_order"
  password: "7bP3PCTcnKXjcHEG"
  charset: "utf8mb4"
  maxIdleConns: 5
  maxOpenConns: 20

rabbitmq:
  url: "amqp://guest:guest@127.0.0.1:5672/"

redis:
  addr: "127.0.0.1:6379"
  password: "Lmx@790816"
  db: 0

security:
  hmacSecret: "demo_hmac_secret"

order:
  shardsPerMonth: 4
  createTimeoutSec: 3

# 上游服务PHP接口地址
upstream:
#  receiveApiUrl: "http://up.test.8dacai.cyou/order/receive"
  receiveApiUrl: "http://localhost:9501/order/receive"
  payoutApiUrl: "http://localhost:9501/order/payout"