server:
  port: "8080"
  mode: "debug"

mysql_main:
  host: "localhost"
  port: 3306
  database: "fourth_wht_pay"
  username: "root"
  password: "Lmx@790816"
  charset: "utf8mb4"
  maxIdleConns: 5
  maxOpenConns: 20

mysql_order:
  host: "localhost"
  port: 3306
  database: "fourth_wht_order"
  username: "root"
  password: "Lmx@790816"
  charset: "utf8mb4"
  maxIdleConns: 5
  maxOpenConns: 20

rabbitmq:
  url: "amqp://guest:guest@127.0.0.1:5672/"

redis:
  addr: "127.0.0.1:6379"
  password: "Lmx@790816"
  db: 3

security:
  hmacSecret: "zVBy6YCo"

order:
  shardsPerMonth: 4
  createTimeoutSec: 3

# 上游服务PHP接口地址
upstream:
#  receiveApiUrl: "http://up.test.8dacai.cyou/order/receive"
  receiveApiUrl: "http://localhost:9501/order/receive"
  payoutApiUrl: "http://localhost:9501/order/payout"